labring/FastGPT

- README.md
- docs/怎么在mac上面运行fastgpt.md
因为教程有部分镜像不兼容arm64，所以写个文档指导新手如何快速在mac上面搭建fast-gpt
> docs:how to run fast-gpt in mac

- admin/package.json
- admin/pnpm-lock.yaml
> chore: fix admin build problem

- README.md
- client/public/docs/chatProblem.md
- client/public/docs/intro.md
- client/public/docs/versionIntro.md
- client/src/components/Layout/navbar.tsx
- client/src/pages/index.tsx
- client/src/pages/tools/index.tsx
If possible, please don't square these two commits into one, because they are two separate commits, I just want to be lazy
> chore: migrate c121914yu to labring

- docs/deploy/mac.md
missing 'source' field in pg init sql
and other optimization
> fix: deploy doc for macOS

- client/src/pages/api/openapi/v1/chat/completions.ts
- client/src/service/utils/chat/index.ts
charset-utf-8应该为charset=utf-8，会导致部分三方优先判断Content-type错误null
> 修正Content-type问题

- client/src/pages/index.tsx
because of github api limit, this number should be regular update
> Update star default number

- .github/workflows/deploy-docs.yml
Signed-off-by: Carson Yang <yangchuansheng33@gmail.com>
> Fix CI workflow

- files/models/ChatGLM2/requirement.txt
make it quick to try the local model.
> add python requirement.txt for running GLM2 model

- docSite/assets/docs/scss/custom/pages/_custom.scss
- docSite/hugo.toml
- docSite/i18n/zh-cn.toml
- docSite/layouts/docs/single.html
- docSite/layouts/partials/docs/gitinfo.html
- docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.content
- docSite/resources/_gen/assets/scss/scss/style.scss_6d90bf46f7cdc038e33af2850006d4ba.content
Enable ‘Edit this page’ link at the bottom of documentation pages
> Docs: enable ‘Edit this page’

- .github/workflows/deploy-preview.yml
> Update deploy-docs-preview workflow

- README.md
文档改为https://doc.fastgpt.in网站访问
> Update README.md 文档改为https://doc.fastgpt.in网站访问

- projects/app/src/web/common/file/api.ts
> PR：解决上传大文件超时的问题

- python/reranker/bge-reranker-base/Dockerfile
- python/reranker/bge-reranker-base/README.md
- python/reranker/bge-reranker-base/app.py
- python/reranker/bge-reranker-base/requirement.txt
add Reranker source code, Dockerfile and readme.
> add reranker

- docSite/content/docs/development/openapi/dataset.md
- projects/app/src/pages/api/core/dataset/collection/create/link.ts
- projects/app/src/pages/api/core/dataset/collection/create/text.ts
- projects/app/src/web/core/dataset/api.ts
> dataset api

- projects/app/src/service/moduleDispatch/agent/extract.ts
BUG when the value of arg is 'false'
> Fixes: Fix logic error when extraction result is "false".

- packages/service/support/permission/auth/common.ts
- projects/app/src/service/common/api/request.ts
- projects/app/src/service/moduleDispatch/tools/http.ts
Add IPv6 support for hostnames with [v6address]:port format.
> Add IPv6 support for hostnames

- docSite/content/docs/development/sealos.md
- packages/service/core/chat/chatItemSchema.ts
- packages/service/core/chat/chatSchema.ts
- packages/service/core/chat/controller.ts
- packages/service/core/dataset/training/schema.ts
- packages/service/support/user/team/teamMemberSchema.ts
- packages/service/support/user/team/teamSchema.ts
- packages/web/package.json
- pnpm-lock.yaml
- projects/app/src/pages/api/core/app/del.ts
- projects/app/src/pages/api/core/chat/clearHistories.ts
- projects/app/src/service/events/generateQA.ts
- projects/app/src/service/events/generateVector.ts
- projects/app/src/service/utils/chat/saveChat.ts
> Fix: pdf version

- docSite/content/docs/development/custom-models/chatglm2.md
- docSite/content/docs/development/custom-models/reranker.md
docs:chatglm2.md the 'requirements' the word error
> docs:Update chatglm2.md and reranker.md the 'requirements' the word error

- docSite/content/docs/development/upgrading/469.md
* move components
* fix
openapi config
doc
> move components to web package (#37)

- .github/workflows/helm-release.yaml
- .github/workflows/preview-image.yml
- .gitignore
- files/helm/fastgpt/.helmignore
- files/helm/fastgpt/Chart.lock
- files/helm/fastgpt/Chart.yaml
- files/helm/fastgpt/templates/NOTES.txt
- files/helm/fastgpt/templates/_helpers.tpl
- files/helm/fastgpt/templates/configmap-config.yaml
- files/helm/fastgpt/templates/configmap-env.yaml
- files/helm/fastgpt/templates/deployment.yaml
- files/helm/fastgpt/templates/hpa.yaml
- files/helm/fastgpt/templates/ingress.yaml
- files/helm/fastgpt/templates/secret-env.yaml
- files/helm/fastgpt/templates/service.yaml
- files/helm/fastgpt/templates/serviceaccount.yaml
- files/helm/fastgpt/templates/tests/test-connection.yaml
- files/helm/fastgpt/values.yaml
I will do more things once this PR got merged.
* Document
* ~~Currently it cannot support v4.6.6+ due to the MangoDB issues.~~
* ~~Cannot update the `config.json`~~
close #1013 
Please add the following to the GitHub secrets before merging this PR:
* `GH_PUBLISH_SECRETS` is the token of below GitHub user
* `GH_USER` is the GitHub user for pushing image
>  feat: support to install fastgpt via helm chart

- .github/workflows/helm-release.yaml
fix https://github.com/labring/FastGPT/issues/1081
> chore: avoid trigger the helm release in main branch

- packages/service/common/file/multer.ts
> fix name from originBucekerName to originBucketName

- packages/service/core/ai/functions/queryExtension.ts
> FIX: Query Extension 历史记录拼接不正确

- projects/app/src/pages/dataset/list/index.tsx
fix the problem that no permission to exported knowledge when the cookie can’t to get.
> fix the problem that no permission to exported knowledge

- packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
- packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
- packages/service/core/workflow/dispatch/tools/http468.ts
- projects/app/src/pages/api/common/file/uploadImage.ts
1. 工具调用支持指定字段数据类型（string, boolean, number） https://github.com/labring/FastGPT/issues/1236
2. 工具调用字段兼容。 https://github.com/labring/FastGPT/issues/1253
3. completions接口size限制 https://github.com/labring/FastGPT/issues/1241
> perf: tool value type and complections body size

- projects/app/src/pages/account/components/Info.tsx
> chatbot url没有配置时，不显示chatbot界面，改善页面一致性

- packages/web/common/system/utils.ts
- packages/web/hooks/useBeforeunload.ts
- packages/web/package.json
- pnpm-lock.yaml
- projects/app/next.config.js
- projects/app/package.json
- projects/app/src/components/ChatBox/components/Empty.tsx
- projects/app/src/components/Layout/index.tsx
- projects/app/src/components/support/user/inform/ImportantInform.tsx
- projects/app/src/components/support/user/inform/SystemMsgModal.tsx
- projects/app/src/pages/_app.tsx
- projects/app/src/pages/chat/components/Empty.tsx
- projects/app/src/pages/login/index.tsx
- projects/app/src/web/context/ChakraUI.tsx
- projects/app/src/web/context/QueryClient.tsx
- projects/app/src/web/context/useInitApp.ts
1. 修复 - 结巴分词库无法引用https://github.com/labring/FastGPT/issues/1311
2. 修复 - window not found提示 https://github.com/labring/FastGPT/issues/1303
> fix @node-rs/jieba and window not found

- projects/app/src/components/core/workflow/Flow/nodes/NodeHttp/index.tsx
https://github.com/labring/FastGPT/issues/1334#issue-2270311464
> fix: issues/1334 useTransition 导致光标刷新后移问题;

- .vscode/settings.json
- packages/global/core/workflow/template/system/globalVariable.ts
- packages/global/core/workflow/template/system/tools.ts
- packages/service/core/workflow/dispatch/utils.ts
- packages/web/hooks/useBeforeunload.ts
- packages/web/hooks/useEditTextarea.tsx
- projects/app/i18n/en/common.json
- projects/app/i18n/zh/common.json
- projects/app/src/components/core/workflow/Flow/ChatTest.tsx
- projects/app/src/components/core/workflow/Flow/nodes/NodeDatasetConcat.tsx
- projects/app/src/components/core/workflow/Flow/nodes/render/NodeCard.tsx
- projects/app/src/components/core/workflow/context.tsx
- projects/app/src/pages/app/detail/components/FlowEdit/Header.tsx
1. Optimize history selection for even numbers
2. Optimize node ui
3. i18n
> Ai histories

- packages/global/core/workflow/template/system/ifElse/constant.ts
- packages/global/core/workflow/utils.ts
- packages/service/core/workflow/dispatch/tools/runIfElse.ts
- projects/app/src/components/core/workflow/Flow/nodes/NodeIfElse/ListItem.tsx
- projects/app/src/components/core/workflow/Flow/nodes/NodeIfElse/index.tsx
- projects/app/src/web/core/workflow/utils.ts
1. conditional render
2. node can run check
3. output
> fix: if else node

- packages/service/core/workflow/dispatch/tools/runIfElse.ts
- projects/app/src/components/core/workflow/Flow/nodes/NodeIfElse/ListItem.tsx
- projects/app/src/components/core/workflow/Flow/nodes/NodeLaf.tsx
- projects/app/src/components/support/laf/LafAccountModal.tsx
1. if else node 输入值为 boolean 的情况
2. laf 绑定
> 4.8 test fix

- projects/app/i18n/en/common.json
- projects/app/i18n/zh/common.json
https://github.com/labring/FastGPT/issues/1037#issuecomment-2081301486
> feat: i18n modify;

- packages/global/core/plugin/httpPlugin/utils.ts
- projects/app/src/components/core/workflow/Flow/nodes/NodeLaf.tsx
> fix: openapi integer & array type

- packages/global/core/plugin/type.d.ts
- packages/global/core/workflow/type/index.d.ts
- packages/service/core/plugin/controller.ts
- packages/service/core/plugin/schema.ts
- packages/service/core/workflow/dispatch/utils.ts
- projects/app/i18n/en/app.json
- projects/app/i18n/zh/app.json
- projects/app/src/components/core/workflow/Flow/nodes/render/NodeCard.tsx
- projects/app/src/components/core/workflow/utils.ts
- projects/app/src/pages/api/core/plugin/update.ts
plugin version update & update var node boolean input #1488
> perf:change plugin version update position

- .npmrc
- Dockerfile
- packages/service/common/string/tiktoken/index.ts
- packages/service/core/dataset/search/utils.ts
- packages/service/package.json
- packages/service/worker/tiktoken/countGptMessagesTokens.ts
- pnpm-lock.yaml
- projects/app/next.config.js
1. 替换 wasm 版本的 token 计算，性能大幅度提高。100w token 计算从3.9s -> 1s
2. 修复 - rerank histories问题 https://github.com/labring/FastGPT/issues/1495
> perf: tiktoken count

- packages/web/hooks/useConfirm.tsx
- projects/app/src/components/support/apikey/Table.tsx
https://github.com/labring/FastGPT/issues/1523
> fix: api key delete bug

- projects/app/next.config.js
> 更新Nextjs配置，更新服务端组件的声明

- projects/app/data/config.json
Embedding names in config file were wrong.
Fixed them according to actual model names.
> Fix: embedding model names in config.json

- LICENSE
Hi there, when I was investigating your architecture and license I found there is a typo in the license. It was fixed by this PR. :)
> Fixed a typo in license

- projects/app/src/pages/api/core/dataset/list.ts
- projects/app/src/pages/dataset/list/component/List.tsx
- projects/app/src/pages/dataset/list/context.tsx
- projects/app/src/pages/dataset/list/index.tsx
- projects/app/src/web/core/dataset/api.ts
> Dataset frontend adjusting (again

- projects/app/src/pages/app/list/components/List.tsx
> fix error toast

- packages/global/core/workflow/template/system/queryExtension.ts
- packages/global/package.json
- packages/plugins/package.json
- packages/service/type.d.ts
- pnpm-lock.yaml
- projects/app/package.json
- projects/app/src/pages/api/system/img/[id].ts
- projects/app/src/pages/app/list/components/context.tsx
- projects/app/src/service/mongo.ts
- projects/sandbox/package.json
- tsconfig.json
1. fix - Change app list tab invalid.
2. fix - @type/nodes version
> 4.8.7 test

- packages/global/support/permission/type.d.ts
- packages/service/support/permission/schema.ts
Fix the Resource Permission Schema
ResourceType Should be a String rather that an Array.
> fix resource permission schema

- packages/service/common/file/image/controller.ts
- packages/service/common/mongo/utils.ts
- pnpm-lock.yaml
- projects/app/src/components/Markdown/CodeLight.tsx
- projects/app/src/components/Markdown/index.module.scss
- projects/app/src/components/Markdown/index.tsx
- projects/app/src/pages/api/core/app/getChatLogs.ts
- projects/app/src/pages/api/core/dataset/exportAll.ts
- projects/app/src/pages/api/core/dataset/training/getDatasetTrainingQueue.ts
- projects/app/src/pages/api/core/dataset/training/getQueueLen.ts
React markdown 9.x unsupport`inline` props. It causes inline code blocks to not display properly.
> Add mongo forward read. Fix markdown code block.

- projects/app/src/pages/api/core/app/version/revert.ts
The pr will fix revert api. Old version workflow cannot revert.
> fix: plugin revert

- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectDatasetParams.tsx
fix: https://github.com/labring/FastGPT/issues/2207
> fix: dataset params default error

- projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
> fix: add check for reset

- packages/global/support/user/inform/type.d.ts
- projects/app/src/service/events/generateQA.ts
- projects/app/src/service/events/generateVector.ts
- projects/app/src/service/events/utils.ts
> chore: use new send notification api

- packages/web/i18n/en/chat.json
- packages/web/i18n/zh/chat.json
- projects/app/src/components/core/app/InputGuideConfig.tsx
- projects/app/src/pages/api/core/chat/inputGuide/delete.ts
- projects/app/src/pages/api/core/chat/inputGuide/deleteAll.ts
- projects/app/src/pages/api/core/chat/inputGuide/update.ts
- projects/app/src/web/core/chat/inputGuide/api.ts
> fix: add delete all input guide lexicon button

- packages/global/core/workflow/utils.ts
> fix: workflow plugin module default input value

- docSite/content/zh-cn/docs/development/custom-models/xinference.md
Repair and supplement document content
> docs: Repair and supplement document content xinference.md

- packages/global/common/string/tools.ts
- packages/global/core/chat/utils.ts
- packages/service/core/ai/functions/queryExtension.ts
- packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
- packages/service/core/workflow/dispatch/agent/runTool/index.ts
- packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
- packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
- packages/service/core/workflow/dispatch/chat/oneapi.ts
- packages/web/i18n/en/common.json
- packages/web/i18n/zh/common.json
- projects/app/package.json
- projects/app/src/pages/app/detail/components/constants.tsx
- projects/app/src/pages/chat/share.tsx
- projects/app/src/pages/chat/team.tsx
1. perf - query extension prompt
2. perf - slice histories preview.
3. fix - share page cannot feedback. https://github.com/labring/FastGPT/issues/2314
4. fix - published i18n error https://github.com/labring/FastGPT/issues/2320
> 4.8.9 test fix

- docSite/content/zh-cn/docs/development/custom-models/bge-rerank.md
> docs(bge-rerank): qa docs

- packages/global/core/workflow/type/index.d.ts
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/HelperLines.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useUtils.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
> feat: add workflow helperline

- packages/global/core/workflow/runtime/type.d.ts
- packages/service/core/workflow/dispatch/tools/http468.ts
http插件body允许text/plain请求体 (#1084)
> feat(http): text/plain is allowed

- packages/global/core/workflow/constants.ts
- packages/global/core/workflow/template/system/http468.ts
- packages/service/core/workflow/dispatch/tools/http468.ts
- packages/web/i18n/en/common.json
- packages/web/i18n/zh/common.json
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
> feat: add http node timeout

- packages/web/i18n/zh/user.json
- projects/app/src/pages/account/components/Info/ConversionModal.tsx
- projects/app/src/pages/account/components/Info/index.tsx
> fix: fix i18n

- package.json
- pnpm-lock.yaml
- scripts/i18n/package.json
- scripts/i18n/query.js
- scripts/i18n/query.ts
- **chore: add i18n query script**
> chore: i18n query script

- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeSystemConfig.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeWorkflowStart.tsx
> fix: change workflow start node output when change file config

- packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
当 `arg===undefined` 时，会导致 `currentTool.function.arguments += arg;` 字符串拼接出问题。
`packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts`
---
LLM api response maybe like this ↓↓↓↓↓↓↓
```
[
{
"id": "f0c2e3b3-2c62-9262-8175-baa275a493e0",
"object": "chat.completion.chunk",
"created": 1724746320,
"model": "qwen",
"choices": [
{
"index": 0,
"delta": {
"role": "assistant",
"content": "",
"tool_calls": [
{
"id": "call_d1744ebbb974447ca80591",
"type": "function",
"function": {
"name": "r9A8ep1I9kxy",
"arguments": "{\"userChatInput\": \"一件事\"}"
}
}
]
}
}
]
},
{
"id": "f0c2e3b3-2c62-9262-8175-baa275a493e0",
"object": "chat.completion.chunk",
"created": 1724746321,
"model": "qwen",
"choices": [
{
"index": 0,
"delta": {
"role": "assistant",
"content": "",
"tool_calls": [
{
"type": …
```
> fix: toolCall.function.arguments maybe undefined

- packages/web/hooks/useScrollPagination.tsx
- projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
- projects/app/src/pages/dataset/detail/components/CollectionCard/TagsPopOver.tsx
1. fix tags manage modal scroll style
2. fix addTagToCollections params
3. fix tags popover search infinite invoke
> fix: tags manage

- projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
1. fix input always required
2. fix can't cancel as tool params
> fix: plugin input

- packages/global/core/chat/type.d.ts
- packages/global/core/workflow/runtime/type.d.ts
- packages/global/core/workflow/runtime/utils.ts
- packages/service/core/workflow/dispatch/index.ts
- packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
- packages/web/i18n/en/common.json
- packages/web/i18n/zh/common.json
- projects/app/src/components/core/chat/components/WholeResponseModal.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeIfElse/ListItem.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/utils.tsx
1. Check circle workflow
2. feat - Update node response
> 4.8.10 fix

- projects/app/src/components/Markdown/index.tsx
- projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatController.tsx
- projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
- projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
- projects/app/src/components/core/chat/components/AIResponseBox.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
- projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
- projects/app/src/web/common/hooks/useCopyData.tsx
1. perf - chatbox performance
2.
> 4.8.10 test

- packages/service/support/permission/app/auth.ts
- packages/service/support/permission/controller.ts
- packages/service/support/permission/dataset/auth.ts
- packages/service/support/permission/user/auth.ts
- packages/web/hooks/usePagination.tsx
- packages/web/i18n/zh/app.json
- projects/app/src/pages/account/components/Promotion.tsx
- projects/app/src/pages/account/components/bill/BillTable.tsx
- projects/app/src/pages/account/components/bill/InvoiceTable.tsx
- projects/app/src/pages/api/core/app/getChatLogs.ts
- projects/app/src/pages/api/support/user/account/loginByPassword.ts
- projects/app/src/pages/app/detail/components/Logs/index.tsx
- projects/app/src/pages/dataset/detail/components/DataCard.tsx
- projects/app/src/types/app.d.ts
- projects/app/src/web/core/app/api.ts
- projects/app/src/web/core/dataset/api.ts
- projects/app/src/web/support/activity/promotion/api.ts
- projects/app/src/web/support/wallet/bill/api.ts
- projects/app/src/web/support/wallet/bill/invoice/api.ts
- **chore: usePagination hook type**
- **feat: chat log show outlinkuid or tmb avatar and name**
- **fix: ts error for pagination**
- **feat: auth root**
> perf: logs, auth root as super admin, etc

- packages/global/support/user/team/group/constant.ts
- packages/service/support/user/team/controller.ts
- projects/app/src/components/support/user/team/TeamManageModal/TeamCard.tsx
- projects/app/src/components/support/user/team/TeamManageModal/components/GroupManage.tsx
- projects/app/src/components/support/user/team/TeamManageModal/components/PermissionManage/AddMemberWithPermissionModal.tsx
- projects/app/src/components/support/user/team/TeamManageModal/components/PermissionManage/index.tsx
- projects/app/src/components/support/user/team/TeamManageModal/components/SelectMember.tsx
- chore: fe adjust 
- fix: remove the member from groups when removing from team
- feat: change the groups avatar when updating the team's avatar
> pref: member group for team

- packages/service/common/string/cheerio.ts
https://github.com/labring/FastGPT/issues/2801
> fix: 网页抓取：正确处理//开头的超链接

- packages/global/core/workflow/runtime/constants.ts
- packages/global/core/workflow/runtime/type.d.ts
- packages/service/core/workflow/dispatch/agent/runTool/index.ts
- packages/service/core/workflow/dispatch/index.ts
- packages/service/core/workflow/dispatch/loop/runLoop.ts
fix https://github.com/labring/FastGPT/issues/2524
> fix:variable not update in nested workflow runs

- projects/app/src/pages/login/index.tsx
fix: https://github.com/labring/FastGPT/issues/2841#issuecomment-2382709079
> fix: login ip check

- files/docker/docker-compose-pgvector.yml
> fix:fastgpt-sandbox image version

- packages/service/common/string/cheerio.ts
https://github.com/labring/FastGPT/issues/1815
> feat: remove style tag when fetching url

- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginOutput.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderOutput/FieldEditModal.tsx
laf函数调用，新增/编辑输出时，显示错误，目前显示为新增/编辑输入
如下图
> typofix:laf函数调用时，弹出文字错误

- packages/service/common/vectorStore/milvus/class.ts
Fix milvus precision issue #2895
> fix: milvus

- packages/global/common/error/errorCode.ts
- packages/plugins/src/bing/template.json
- packages/service/common/middle/entry.ts
- packages/service/common/middle/reqFrequencyLimit.ts
- packages/service/common/system/frequencyLimit/schema.ts
- packages/service/common/system/frequencyLimit/utils.ts
- packages/service/core/workflow/dispatch/loop/runLoop.ts
- packages/service/core/workflow/dispatch/tools/http468.ts
- projects/app/.env.template
- projects/app/src/components/core/app/ScheduledTriggerConfig.tsx
- projects/app/src/pages/api/core/dataset/searchTest.ts
- projects/app/src/web/common/system/doc.ts
- projects/app/src/web/core/workflow/utils.ts
1. perf - QPS limit api
2. fix - http response json path support
> 4.8.12 test fix

- projects/app/src/web/common/utils/voice.ts
- Add MediaSource support detection function
- Implement fallback solution for browsers that don't support MediaSource:
- For single audio: Read full stream before playing
- For segmented audio: Wait until all text is received then play as one audio
- Improve code robustness and browser compatibility
> feat(voice): add fallback for browsers without MediaSource support

- docSite/content/zh-cn/docs/development/upgrading/4813.md
- projects/app/Dockerfile
https://github.com/labring/FastGPT/issues/3054
https://github.com/labring/FastGPT/issues/3064
> perf: dockerfile proxy

- packages/service/core/workflow/dispatch/tools/http468.ts
fix: https://github.com/labring/FastGPT/issues/3089
> fix: http tool response

- packages/plugins/register.ts
- packages/plugins/src/Doc2X/PDF2text/index.ts
- packages/plugins/src/Doc2X/PDF2text/template.json
- packages/service/core/workflow/dispatch/tools/http468.ts
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
- projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
- projects/app/src/service/common/system/volumnMongoWatch.ts
- projects/app/src/service/core/app/plugin.ts
- projects/app/src/service/mongo.ts
> perf: doc2x plugins

- projects/app/src/pages/app/list/index.tsx
- projects/app/src/pages/dataset/list/index.tsx
Close: https://github.com/labring/FastGPT/pull/3195
> fix: create btn permission

- projects/sandbox/Dockerfile
修复打包异常，异常信息：
Step 17/28 : COPY package.json pnpm-workspace.yaml /app When using COPY with more than one source file, the destination must be a directory and end with a /
> Fix: Sandbox Dockerfile

- packages/global/core/chat/api.d.ts
- projects/app/src/components/core/chat/ChatContainer/ChatBox/components/FeedbackModal.tsx
- projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
- projects/app/src/pages/app/detail/components/Publish/Link/SelectUsingWayModal.tsx
- projects/app/src/pages/chat/share.tsx
- projects/app/src/web/common/utils/i18n.ts
- projects/app/src/web/core/chat/context/chatRecordContext.tsx
fix: https://github.com/labring/FastGPT/issues/3279
> Fix share page feedback auth

- docSite/content/zh-cn/docs/development/intro.md
- packages/global/common/string/tools.ts
- packages/global/core/workflow/runtime/utils.ts
- packages/global/package.json
- packages/plugins/src/drawing/baseChart/index.ts
- packages/plugins/src/drawing/baseChart/template.json
- packages/service/core/workflow/dispatch/tools/http468.ts
- pnpm-lock.yaml
fix: https://github.com/labring/FastGPT/issues/3529
> fix: charts plugins

- projects/app/src/pages/api/core/app/getChatLogs.ts
- projects/app/src/pages/api/core/app/list.ts
- projects/app/src/pages/api/core/dataset/collection/listV2.ts
- projects/app/src/web/core/dataset/api.ts
- **fix: collection list api format**
> fix: collection list api old version

- packages/global/core/workflow/runtime/utils.ts
- packages/service/core/workflow/dispatch/index.ts
> fix interactive edge

- docSite/content/zh-cn/docs/development/upgrading/4820.md
- packages/global/core/chat/adapt.ts
- packages/service/core/chat/utils.ts
- packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
Close: https://github.com/labring/FastGPT/issues/3667
> perf: supplement assistant empty response

- packages/global/core/ai/model.ts
- packages/service/common/mongo/index.ts
- packages/service/core/ai/audio/transcriptions.ts
- packages/service/core/ai/config/utils.ts
- packages/service/core/ai/embedding/index.ts
- packages/service/core/ai/rerank/index.ts
- packages/service/core/dataset/data/dataTextSchema.ts
- packages/web/i18n/en/account.json
- packages/web/i18n/zh-CN/account.json
- packages/web/i18n/zh-Hant/account.json
- projects/app/public/docs/chatProblem.md
- projects/app/src/components/Layout/index.tsx
- projects/app/src/pageComponents/account/model/ModelConfigTable.tsx
- projects/app/src/pages/api/core/ai/model/test.ts
1. fix:  rerank auth token https://github.com/labring/FastGPT/issues/3694
2. perf: On some system, the binding notification prompt is hidden
3. feat: The output reason field is configuable https://github.com/labring/FastGPT/issues/3701
4. fix: Mongo4.x cann't sync index https://github.com/labring/FastGPT/issues/3695
> 4.8.20 update

- projects/app/src/pages/api/core/app/list.ts
- projects/app/src/pages/api/core/dataset/list.ts
> fix: app/dataset list api return private flag

- projects/app/src/pageComponents/account/TeamSelector.tsx
- projects/app/src/pages/account/info/index.tsx
- projects/app/src/pages/account/team/index.tsx
fix: [3788](https://github.com/labring/FastGPT/issues/3788)
> fix: refresh memberlist when switching account

- packages/service/common/file/gridfs/controller.ts
- packages/service/package.json
- packages/service/support/permission/controller.ts
- packages/service/support/permission/publish/authLink.ts
- packages/service/support/permission/teamLimit.ts
- projects/app/src/pages/api/admin/initv481.ts
- projects/app/src/pages/api/support/outLink/delete.ts
I have checked the migration guide: https://mongoosejs.com/docs/migrating_to_8.html#removed-overwrite-option-for-findoneandupdate
There are several breaking changes.
> chore: upgrade mongoose to v8.10.x for security

- packages/service/core/dataset/search/controller.ts
当在非工作流的环境下进行知识库检索问题优化时会获取不到上下文
> fix: 修复知识库问题优化无效的BUG

- packages/service/core/workflow/dispatch/tools/http468.ts
fix: https://github.com/labring/FastGPT/issues/4066
> perf: HTTP node jsonBody support  \n

- deploy/docker/docker-compose-milvus.yml
- deploy/docker/docker-compose-pgvector.yml
- deploy/docker/docker-compose-zilliz.yml
- docSite/content/zh-cn/docs/development/upgrading/490.md
https://github.com/labring/aiproxy
> feat: aiproxy repo moved

- packages/web/hooks/useLinkedScroll.tsx
- projects/app/src/components/core/chat/components/AIResponseBox.tsx
- projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteItem.tsx
- projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteReader.tsx
- projects/app/src/pageComponents/dataset/ApiDatasetForm.tsx
> fix loadInitData refresh

- README.md
- docSite/content/zh-cn/docs/development/modelConfig/ppio.md
Add new documentation for integrating models via PPIO LLM API.
> docs: Add PPIO integration documentation

- packages/service/core/app/utils.ts
* fix dataset search node reference save
* rewrite
---------
> 4.9.1 fix dataset (#4279)

- plugins/model/pdf-mistral/.env
- plugins/model/pdf-mistral/README.md
- plugins/model/pdf-mistral/api_mp.py
- plugins/model/pdf-mistral/requirements.txt
增加一个转换器，像调用marker pdf一样调用mistral-ocr在线api
https://mistral.ai/news/mistral-ocr
> add mistral-ocr support as a plugin like pdf-marker

- packages/global/support/user/team/org/api.d.ts
- packages/global/support/user/team/org/constant.ts
- packages/global/support/user/team/org/type.d.ts
- packages/service/support/permission/auth/org.ts
- packages/web/components/common/Avatar/AvatarGroup.tsx
- projects/app/src/components/support/permission/ChangeOwnerModal/index.tsx
- projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
- projects/app/src/pageComponents/account/team/GroupManage/GroupInfoModal.tsx
- projects/app/src/pageComponents/account/team/GroupManage/GroupManageMember.tsx
- projects/app/src/pageComponents/account/team/GroupManage/GroupTransferOwnerModal.tsx
- projects/app/src/pageComponents/account/team/GroupManage/index.tsx
- projects/app/src/pageComponents/account/team/MemberTable.tsx
- projects/app/src/pageComponents/account/team/OrgManage/OrgInfoModal.tsx
- projects/app/src/pageComponents/account/team/OrgManage/OrgMemberManageModal.tsx
- projects/app/src/pageComponents/account/team/OrgManage/OrgMoveModal.tsx
- projects/app/src/pageComponents/account/team/OrgManage/OrgTree.tsx
- projects/app/src/pageComponents/account/team/OrgManage/index.tsx
- projects/app/src/pageComponents/account/team/context.tsx
- projects/app/src/web/support/user/team/org/api.ts
- projects/app/src/web/support/user/team/org/hooks/useOrg.tsx
- **feat: change group owner api**
- **pref: member/org/group**
> pref: member/group/org

- projects/app/src/components/common/folder/Path.tsx
fix: https://github.com/labring/FastGPT/issues/4303
> fix: simple app all_app button

- projects/app/src/pageComponents/account/model/Channel/ModelTest.tsx
- Add independent loading status for each model test button
- Replace the original shared loading state design
- Optimize the status logic of batch test buttons
- I mprove the interactive experience of users testing multiple models
> feat: Add support for independent loading states to optimize user experience during model testing

- packages/global/core/workflow/runtime/type.d.ts
- packages/service/core/workflow/dispatch/plugin/run.ts
- packages/service/core/workflow/dispatch/plugin/runApp.ts
- packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
- projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/ChatTest.tsx
> fix child app update variables

- projects/app/package.json
https://github.com/labring/FastGPT/issues/4389
> chore: edit the version number

- docSite/content/zh-cn/docs/guide/admin/sso.md
should be EXTERNAL_USER_SYSTEM_BASE_URL
> fix: sso.md

- packages/global/common/system/types/index.d.ts
* pro migration
* reuse customPdfParseType
> pro migration (#4388)

- packages/service/package.json
- pnpm-lock.yaml
remove deprecated dependency: canvas@2
> deps: bump pdfjs-dist to 4.10.38

- packages/global/core/workflow/node/constant.ts
- packages/web/components/common/MySelect/MultipleSelect.tsx
- packages/web/i18n/en/common.json
- packages/web/i18n/zh-CN/common.json
- packages/web/i18n/zh-Hant/common.json
- projects/app/src/components/core/chat/components/Interactive/InteractiveComponents.tsx
- projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
- projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
- projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
- projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectMulti.tsx
> feat: 表单组件增加多选

- projects/app/src/pageComponents/app/detail/Publish/Link/SelectUsingWayModal.tsx
…omponent to add support for microphones.
> Fixed: Updated the iframe allow property in the SelectUsingWayModal

- packages/service/common/string/cheerio.ts
- packages/service/worker/htmlStr2Md/utils.ts
https://github.com/labring/FastGPT/issues/4780
通过url新建文本数据集时，将video标签转换成```[Video](src)```的格式
> feat: add html video tag convertion

- packages/service/core/workflow/dispatch/agent/runTool/index.ts
- packages/service/core/workflow/dispatch/index.ts
fix bug while using both toolselect and interactive nodes
> fix: improve handling of interactive node responses in workflow dispatch

- projects/app/src/pageComponents/chat/ChatQuoteList/index.tsx
> fix quote reader duplicate rendering

- projects/app/src/pageComponents/dataset/detail/Import/components/FileSelector.tsx
- projects/app/src/pageComponents/dataset/detail/components/FileSelector.tsx
fix: https://github.com/labring/FastGPT/issues/4891
> Fix the incompatibility of drag-and-drop upload to Windows

- packages/web/styles/theme.ts
fix issue: https://github.com/labring/FastGPT/issues/4722
> fix: resizer.svg load error

- packages/global/core/workflow/template/system/sandbox/constants.ts
- projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeCode.tsx
> fix:sandbox misspelling

- packages/service/core/app/mcp.ts
> fix: update input schema structure in getTools method

- packages/service/core/app/mcp.ts
- packages/service/core/app/schema.ts
- packages/service/core/app/version/schema.ts
response: #5070  @liukewia。
设计理由：优先保障运行时减少计算量。
> Mcp db fix

- packages/service/common/file/csv.ts
- packages/service/support/permission/controller.ts
- packages/service/support/user/session.ts
- projects/app/next.config.js
- projects/app/src/pages/api/core/app/exportChatLogs.ts
- projects/app/src/pages/api/core/dataset/collection/export.ts
- projects/app/src/pages/api/core/dataset/exportAll.ts
- projects/app/src/pages/api/support/user/account/resetExpiredPsw.ts
- projects/app/src/pages/api/support/user/account/updatePasswordByOld.ts
1.  fix csv injection
2.  add security headers config
3.  delelet user all session after update password
> fix vulnerability

- .github/workflows/docs-preview.yml
- .github/workflows/fastgpt-preview-image.yml
- docSite/content/zh-cn/docs/development/design/design_plugin.md
- docSite/content/zh-cn/docs/guide/plugins/design_plugin.md
- **chore: update docker-compose.yamls**
- **docs(plugin): add design document for plugin**
> docs: update plugin design doc

- projects/app/src/pages/api/core/dataset/collection/listV2.ts
> fix:collection search

- projects/app/src/components/core/app/formRender/LabelAndForm.tsx
- projects/app/src/components/core/app/formRender/utils.ts
- projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInputForm.tsx
- projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariablePopover.tsx
Close: https://github.com/labring/FastGPT/pull/5244
> fix: variables init

- projects/app/src/components/support/user/safe/SendCodeAuthModal.tsx
- projects/app/src/pageComponents/login/LoginModal.tsx
- projects/app/src/pageComponents/login/index.tsx
1. make the overflowed content hidden in the login container, grow the flex content
2. add key down event of the captcha modal's input
> fix: fix the login container; fix the incorrect input of captcha enter trigger

- projects/mcp_server/Dockerfile
fix missing build mcp image args
> fix: missing build mcp image args

- projects/app/src/pageComponents/app/detail/SimpleApp/AppCard.tsx
- projects/app/src/pageComponents/chat/ChatHeader.tsx
- projects/app/src/pageComponents/chat/ChatTeamApp/List.tsx
- projects/app/src/pageComponents/chat/ChatWindow/AppChatWindow.tsx
- projects/app/src/pageComponents/chat/ChatWindow/HomeChatWindow.tsx
- projects/app/src/pageComponents/chat/SliderApps.tsx
- projects/app/src/pageComponents/chat/useChat.ts
- projects/app/src/pageComponents/dashboard/apps/List.tsx
- projects/app/src/web/core/chat/context/chatSettingContext.tsx
> fix: sync pane with URL appId vs Home appId to avoid cross-tab interference

- projects/app/src/components/common/secret/HeaderAuthConfig.tsx
> fix: increase MCP auth config value field maxLength

- .gitignore
- packages/global/core/dataset/search/utils.ts
- packages/service/core/dataset/search/controller.ts
- packages/service/core/workflow/dispatch/dataset/concat.ts
原来：1/(weight+rank)
修改后：weight * 1/(60+rank)
将weight 提取出来比较符合 rrf 的定义
> Modified the weight calculation method when performing RRF merging

- deploy/README.md
- deploy/docker/cn/docker-compose.milvus.yml
- deploy/docker/cn/docker-compose.oceanbase.yml
- deploy/docker/cn/docker-compose.pg.yml
- deploy/docker/cn/docker-compose.zilliz.yml
- deploy/docker/global/docker-compose.milvus.yml
- deploy/docker/global/docker-compose.oceanbase.yml
- deploy/docker/global/docker-compose.pg.yml
- deploy/docker/global/docker-compose.ziliiz.yml
- deploy/init.mjs
- deploy/templates/docker-compose.prod.yml
- deploy/templates/vector/milvus.txt
- deploy/templates/vector/ob.txt
- deploy/templates/vector/pg.txt
- document/public/deploy/docker/cn/docker-compose.milvus.yml
- document/public/deploy/docker/cn/docker-compose.oceanbase.yml
- document/public/deploy/docker/cn/docker-compose.pg.yml
- document/public/deploy/docker/cn/docker-compose.zilliz.yml
- document/public/deploy/docker/global/docker-compose.milvus.yml
- document/public/deploy/docker/global/docker-compose.oceanbase.yml
- document/public/deploy/docker/global/docker-compose.pg.yml
- document/public/deploy/docker/global/docker-compose.ziliiz.yml
fixing: https://github.com/labring/FastGPT/issues/5718
> fix: docker-compose pg_url removal; depends on pg -> vectorDB
