.github/workflows/release.yml

fix #16 
Describe: Using ci to auto build arm64 and amd64 image when push in main branch.
First you should set secret.GH_PAT in ci secrets,the GH_PAT get from github,
here is the tutorial，https://blog.csdn.net/u014175572/article/details/55510825
I have test in my repo,https://github.com/xiao-jay/FastGPT/actions/runs/4772746401,after ci running,will get a fast-gpt package.

ci: build arm and amd image when push main branch

---

.github/workflows/release.yml

now image will not auto link FastGPT repo,add `org.opencontainers.image.source` label in image will auto link FastGPT repo

ci: let image build by ci auto link to fastgpt repo

---

src/service/plugins/searchKb.ts

修复 filterSystemPrompt为'\n'时, 判断有问题

fix: filter system prompt 字符串判空

---

README.md

docs: add One API

---

client/src/service/utils/chat/index.ts

在处理接口返回的时候多进行了一次判断流返回是否为json，如果不为json存储起来并在下一次继续进行判断，组装成功或出现完整json时一个流程结束回到原始状态，极端情况下可能出现截断成3截以上情况也可以兼容

修复使用代理情况下走流返回，出现的返回吞字问题

---

README.md
README_en.md
README_ja.md

I created Japanese translated README.

Docs: Add Japanese README

---

Dockerfile

Merge two apk install commands and use the `--no-cache` parameter to minimize the temporary files left in the Docker image.
I also noticed that there were different apk install processes in the Dockerfile. The second one has the process to replace https with http in `/etc/apk/repositories` before the installation, but the first one doesn't, meaning the process is unnecessary.

Optimize apk install process in Dockerfile

---

packages/service/support/permission/controller.ts

Adjust the api authentication sequence to preferentially process "authentication" to avoid incorrect authentication caused by cookies

---

projects/app/src/pages/dataset/detail/components/Import/QA.tsx

知识库-导入-QA 中提示可以选择 md 和 html 文件，但是确无法选择 md 和 html 文件。是因为 QA.tsx中定义的fileExtension变量少写了一个逗号，我加上了这个逗号。

fix: 知识库 QA 导入无法选择 md 和 html 文件

---

packages/service/core/dataset/training/schema.ts

bugfix: 修复训练任务过早过期的问题
-> 改成了正确的7天过期时间

bugfix: 修复训练任务过早过期的问题

---

README.md

Followup: https://github.com/labring/FastGPT/pull/786
The badge is pointing to my fork. Now it's points to the `labring/FastGPT`.

fix: badge points to right repo now

---

docSite/content/docs/development/configuration.md

用最新的配置文件4.6.8 ，对话选gpt-4-turbo 报错：
null max_tokens is too large: 62500. This model supports at most 4096 completion tokens, whereas you provided 62500. (request id: 20240202110253407344738SmDnkwX1) 原因是官方gpt-4-turbo 最大的返回token 4096.

change gpt-4-turbo maxResponse configuration template

---

docSite/content/docs/development/custom-models/reranker.md

原docker启动命令启动后的容器只能使用CPU运行。本次修改增加了GPU参数，并提供docker-compose.yml示例

reranker.md优化docker启动命令，并增加docker-compose.yml示例

---

projects/app/src/service/events/generateQA.ts

> 当前QA生成的Q格式为`Q\d+`，因此将匹配Q和A的正则表达式调整为 `Q\d` 作为判断
----
**example:**
```
text = 'Q1: 什么是SQL？\nA1: SQL代表结构化查询语言（Structured Query Language），它是用于管理关系型数据库系统的标准化语言。SQL允许用户执行各种任务，如从数据库中检索数据、插入新数据、更新现有数据以及删除数据。通过SQL，用户可以与数据库进行交互，并执行诸如查询、更新、插入和删除等操作。'
```
> old: `/Q\d+:(\s*)(.*)(\s*)A\d+:(\s*)([\s\S]*?)(?=Q|$)/g;`
```
Q: 什么是SQL？
A: S
```
> new:  `/Q\d+:(\s*)(.*)(\s*)A\d+:(\s*)([\s\S]*?)(?=Q\d|$)/g;`
```
Q: 什么是SQL？
A: SQL代表结构化查询语言（Structured Query Language），它是用于管理关系型数据库系统的标准化语言。SQL允许用户执行各种任务，如从数据库中检索数据、插入新数据、更新现有数据以及删除数据。通过SQL，用户可以与数据库进行交互，并执行诸如查询、更新、插入和删除等操作。
```

fix: 知识库QA生成，答案中有“Q”会导致提前截断。

---

docSite/content/docs/development/docker.md

original code is a bad url with '404 NOT FOUND' return.  fix docker-compose download url, add 'v' before docker-compose version

docs: Fixed misspelled word "v"

---

projects/app/src/service/moduleDispatch/agent/classifyQuestion.ts
projects/app/src/service/moduleDispatch/agent/extract.ts

It seems that classifyQuestion and extract modules do not process the chat histories correctly. 
It passes **Object** rather than the **text** to the LLM

Fix history in classifyQuestion and extract modules

---

packages/service/common/file/utils.ts
projects/app/src/pages/api/system/img/[id].ts

1.  添加根据 base64 首字母推测图片类型的函数。
2. 修复由于图片下载丢失原类型（统一为 image/jpeg），导致的 claude3 多模态接口无法使用的问题。 #1038

fix: claude3 image type verification failed (#1038)

---

projects/app/public/js/iframe.js

修复拖动聊天图标容易中断问题

---

packages/service/core/chat/utils.ts

修复通过 API 访问调用多模态模型应用接口，传入 `Data URI` 由于图片类型 `undefined` 接口报错的问题。  #1217

fix: base64 image undefined

---

projects/app/src/components/core/workflow/context.tsx

在节点删除时（分类节点删除分类等），edge等sourceHandle，targetHandle错误导致无法删除边。负面影响是可能在删除、新增类别后仍然触发下游节点

Fixes: fix edge handler with onDelEdge

---

packages/web/components/common/MyDrawer/MyRightDrawer.tsx
projects/app/src/components/core/workflow/Flow/hooks/useDebug.tsx
projects/app/src/pages/dataset/detail/components/Import/components/PreviewChunks.tsx

fix: chunk preview drawer can not scroll, common drawer content scroll should decide by content;

fix: chunk preview drawer can not scroll

---

projects/app/src/components/Markdown/img/Image.tsx

实现在移动端，点击AI回答的图片后，可以通过双指放大缩小移动图片的功能，只用原生代码修改了projects/app/src/components/Markdown/img/Image.tsx文件，未引入第三方库，方便合并到主分支，减少冲突的可能，关联Issue #1813

添加移动端手势放大图片的功能

---

projects/app/src/pages/chat/share.tsx

添加了通过使用iframe引用chat页面时隐藏头部的功能，主要是应对多个iframe引用多个页面的情况，具体应用情况看下图吧：
我知道这功能挺傻的，但老板要加╮(╯▽╰)╭
我想，还是提个PR，看看会不会被合到主代码里，免得以后主代码升级了，我都必去拉源码来本地编译开发。
唉~，生活不易！

添加AI对话时隐藏头部的功能，主要是适配移动端

---

packages/global/core/ai/prompt/agent.ts

I find `<Context/>` , i think this is wrong tag.

fix(prompt): typo template tag

---

packages/global/common/file/image/type.d.ts
packages/service/common/file/image/controller.ts
projects/app/src/pages/api/system/img/[id].ts

在解析文件的过程中，我发现了类似于 `image/tiff` 的图片格式，我尝试将解析图片的 base64 `mime` 类型记录在 `metadata` 中，以便响应正确的类型，并且后续如果需要对图片进行更多处理的话，可以用到这个字段。

feat(image): metadata support image mime type

---

projects/app/src/pages/api/core/app/plugin/getPreviewNode.ts

In the former code.
A user who accesses the plugin should have Write Permission, which should be Read Permission instead.

fix: app get readable team plugin error

---

projects/app/src/pages/dataset/detail/components/Import/components/FileSelector.tsx
projects/app/src/pages/dataset/detail/components/Import/diffSource/FileLocal.tsx

After the file is uploaded, the progress is forcibly updated, and the progress is not used to determine whether the upload is complete.
May solve https://github.com/labring/FastGPT/issues/2148

perf: dataset upload process render

---

packages/service/core/dataset/collection/utils.ts

When the knowledge base input, select the type is the link input method, preview the segment, the custom segment takes effect, but click Next to upload, the custom segment does not take effect, according to the source code analysis, did not pass the custom separator to the slice method.

Fix: Custom delimiter does not take effect when document type is link

---

packages/service/common/string/cheerio.ts

Expose a load function for pro-version, thus pro-version is unnecessary to install cheerio to analyze the HTML content.

feat: dynamic website crawler

---

packages/global/core/workflow/runtime/utils.ts
packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
packages/service/core/workflow/dispatch/index.ts
packages/web/styles/theme.ts
projects/app/Dockerfile
projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
projects/app/src/components/core/chat/ChatContainer/ChatBox/type.d.ts
projects/app/src/components/core/chat/ChatContainer/ChatBox/utils.ts
projects/app/src/components/core/chat/ChatContainer/useChat.ts
projects/app/src/components/core/chat/components/AIResponseBox.tsx
projects/app/src/pages/account/components/Individuation.tsx
projects/app/src/pages/api/core/chat/chatTest.ts
projects/app/src/pages/app/detail/components/useChatTest.tsx
projects/app/src/pages/login/provider.tsx
projects/app/src/pages/login/sso.tsx

1. 修复 - 用户选择的判断逻辑和结束逻辑
2. 修复 - 重开对话，无法修改 started 标记

4.8.10 perf

---

projects/app/src/components/core/chat/ChatContainer/ChatBox/utils.ts

在调试页面，当调试时，大模型没有反回值，会导致页面崩溃。
lastMessageValue取值时需要提前判断空值，否则取出来的值为空对象。

Fixs:当最后一条数据因大模型没返回数据时导致调试时前端报错。

---

python/bge-rerank/README.md

Fix typo location of python bge-rerank

Fix typo location of python bge-rerank

---

projects/app/src/pages/api/core/dataset/collection/sync/link.ts

Fixed an issue where chunk splitter were lost when clicking on the link sync

fixSyncLinkChunkSplitterBug

---

docSite/content/zh-cn/docs/development/docker.md

原先 config.json 的地址是：
https://github.com/labring/FastGPT/blob/main/projects/app/data/config.json
如果没有考虑太多，直接 wget "https://github.com/labring/FastGPT/blob/main/projects/app/data/config.json"，则会下载到网页版的 `config.json`。这不是一个 json 文件，而是 github 的网页。
所以，修改为 `https://raw.githubusercontent.com/labring/FastGPT/refs/heads/main/projects/app/data/config.json` 更加合理

updated: docs/docker.md，修改 config.json 的地址

---

docSite/content/zh-cn/docs/development/upgrading/4811.md
packages/service/core/workflow/dispatch/tools/http468.ts
packages/service/core/workflow/dispatch/utils.ts
projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/ToolHandle.tsx
projects/app/src/web/common/hooks/useSpeech.ts

fix: https://github.com/labring/FastGPT/issues/1392

IOS safari whisper support

---

packages/service/common/vectorStore/milvus/class.ts

disable autoId when creating collections.
generate a safe integer id for collection when inserting.

fix: milvus

---

scripts/postinstall.sh

/app # pnpm i Scope: all 8 workspace projects Lockfile is up to date, resolution step is skipped Already up to date . postinstall$ sh ./scripts/postinstall.sh │ mkdir: can't create directory 'projects/app/tmp': File exists └─ Failed in 16ms at /app  ELIFECYCLE  Command failed with exit code 1.

解决第二次运行pnpm i时报错：File exists

---

packages/web/common/file/utils.ts

window下编辑csv文件后保存，会修改编码格式
wps下另存为没有办法选择编码格式
很多用户不会修改编码格式
因此兼容非utf-8格式的批量导入，无mac电脑，无法测试，麻烦楼主测试一下

Fix garbled code

---

packages/service/common/file/image/controller.ts

在当前实现中，当设置了子路径（NEXT_PUBLIC_BASE_URL）时，图片文件的读取路径不正确，导致图片无法正常显示或访问。具体表现为生成的图片 URL 缺少子路径部分，导致请求失败。
**解决方案**：
在生成图片 URL 时，增加对 NEXT_PUBLIC_BASE_URL 环境变量的处理 `${process.env.NEXT_PUBLIC_BASE_URL || ''}`，确保在设置子路径时，URL 能够正确包含子路径部分。
```js
return `${process.env.FE_DOMAIN || ''}${process.env.NEXT_PUBLIC_BASE_URL || ''}${imageBaseUrl}${String(_id)}.${extension}`;
```

修复：设置NEXT_PUBLIC_BASE_URL时，图片文件读取URL不正确

---

projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx

* 表单输入的数字输入框无法输入0
* 插件输入的数字输入框无法输入0

fix: 插件输入和表单输入的数字输入框无法输入0

---

packages/service/core/ai/config/utils.ts

本地windows平台开发，加载model列表出现两次盘符导致加载失败，修改代码确保生成的路径不会包含重复的盘符，从而避免 ENOENT 错误。

Load models error Error: ENOENT: no such file or directory, scandir

---

docSite/content/zh-cn/docs/development/openapi/dataset.md

V2版本“获取集合列表”接口的path区分了大小写，使用/api/core/dataset/collection/listv2会返回404，必须使用大写V

fix document

---

packages/service/worker/readFile/parseOffice.ts

更新本地导入pptx文件提示文件编码错误
The argument 'windows-1252' is invalid encoding. Received 'encoding'

fix: upload office file (.pptx) encoding error

---

packages/service/common/mongo/init.ts

fix #3744
refer: https://mongoosejs.com/docs/guide.html#strictQuery
TLDR: strictQuery option should be false. Then when you pass something, which is not in the Schema, the query will not be filtered and pass to mongodb directly. Thus it will not query the whole document.
```ts
// strictQuery === true
Model.find({ somethingNotInSchema: 'something' }) // the whole document
// strictQuery === false
Model.find({ somethingNotInSchema: 'something' }) // empty
```

fix: mongoose strictquery to false

---

projects/app/src/pages/api/core/app/exportChatLogs.ts

fix: chat detail order in export chat logs

---

packages/service/common/file/gridfs/utils.ts

如果 Buffer.concat() 被频繁调用，尤其是在处理大量数据时，可能会导致内存分配压力增大，从而影响性能。 测试大于100M的PDF文件上传解析会导致/api/core/dataset/collection/create/fileId接口长时间无响应，其他接口也处于hang住的状态，导致整个服务不可用。 使用一次性拼接后问题解决

fix: 优化读取mongo文件性能，解决因执行Buffer.concat过多造成等待导致整个服务hang住的

---

packages/global/core/app/utils.ts

部分参数 (Reasoning, TopP, StopSign, ResponseFormat, JsonSchema) 保存完后重新进入不显示，并且在某些情况（包括但不限于保存应用操作）会导致用空值覆盖数据库的值从而丢失这个参数值

fix: 修复部分参数丢失的问题

---

packages/service/core/workflow/dispatch/agent/extract.ts

fix issue #3915 
有些模型不支持
```JSON
{"type": "arrayString"}
``` 
统一用这种
```JSON
{
"type": "array",
"items": {
"type": "string"
}
}
```
就好了

fix: 文本提取不支持arrayString,arrayNumber等jsonSchema

---

projects/app/src/components/core/chat/ChatContainer/ChatBox/components/QuoteList.tsx

当使用免登录窗口 / API 调用一个含有“知识库搜索”节点的工作流时，在“对话日志”中查看“知识库搜索”节点的完整响应会提示“无权操作该数据集”，非免登录窗口/API调用的日志则可正常显示
截图为使用 [官网版本 FastGPT](https://cloud.tryfastgpt.ai/) 查看免登录窗口的对话日志时的错误提示：
经检查为传递的 `chatId` 参数有误，已进行更正

fixed: permission error when viewing database search node responses

---

packages/service/core/workflow/dispatch/loop/runLoop.ts

when the loop input array is too long, the log always show the max length is 50.

Fix: log error when the loop input array is too long

---

patches/mdast-util-gfm-autolink-literal@2.0.1.patch
pnpm-lock.yaml
pnpm-workspace.yaml

Compatibility patch for Safari versions below 16.4

fix: Add patch for mdast-util-gfm-autolink-literal@2.0.1

---

projects/sandbox/src/sandbox/constants.ts
projects/sandbox/src/sandbox/utils.ts

我在使用fastgpt的代码执行节点时，因为前置节点从http请求中获得了大量的数据，导致python代码无法正确执行。
我将python代码从字符串形式执行修改为写入临时文件的方式执行，以便支持大数据量参数的执行。
When using the code execution node in FastGPT, I encountered an issue where the Python code failed to execute correctly due to the large amount of data obtained from the HTTP request in the preceding node.
I modified the Python code execution from a string-based approach to writing it into a temporary file for execution, in order to support the execution of large data parameters.

feat: python sandbox execute with a temporary file

---

packages/service/core/workflow/dispatch/utils.ts

1，字符串数组的值可能包含转义斜杠会导致typeof value为string，结果变量更新后的值变形为多层数组嵌套而无法使用（[[]]）。这个修复解决了这个问题。 
2，另外对整体的逻辑做了梳理和整理，更加清晰易懂

变量更新组件处理字符串数组错误修复

---

.github/workflows/docs-deploy-cf.yml
.github/workflows/docs-deploy-kubeconfig.yml
.github/workflows/docs-preview.yml
.github/workflows/fastgpt-build-image-personal.yml
.github/workflows/fastgpt-preview-image.yml
.github/workflows/helm-release.yaml

Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101

fix: update workflow to use ubuntu-24.04 for consistency across all jobs

---

packages/service/core/chat/saveChat.ts
projects/app/src/pages/api/v1/chat/completions.ts

程序api调用场景下，如果大量调用带有图片或视频，产生的聊天记录会导致后台mongo数据库异常。这个修改给api客户端一个禁止生成聊天记录的选项，避免这个后果。

api调用场景下，如果大量调用带有图片或视频，产生的聊天记录会导致后台mongo数据库异常

---

deploy/docker/docker-compose-milvus.yml

修复默认使用aliyuncs阿里云docker镜像部署报错的问题，现默认使用dockerhub官方源。

Change the default MongoDB image source to Docker Hub.

---

projects/app/src/components/Markdown/codeBlock/iframe-html.tsx

#4966 
Fixed the issue where anchor (`<a>`) tags in reply content could not properly open links in a new tab or window. For security reasons, it is recommended to add `rel="noopener"` when using `target="_blank"` in `<a>` tags.

fix: Fixed the issue where anchor (`<a>`) tags in reply content could not properly open links in a new tab or window. 

---

.gitignore
packages/service/core/ai/functions/queryExtension.ts

- 使用子模优化算法替代简单的查询生成方式
- 实现懒贪心算法进行最优查询选择
- 引入余弦相似度和边际增益计算，提高查询多样性
- 新增 `generateCount` 参数控制初始查询数量
- 修改提示词模板以支持动态查询数量
- 增加查询数量的验证逻辑
- 集成向量嵌入生成功能
- 支持原始查询和候选查询的向量处理
- 实现向量比较和选择逻辑

查询问题的扩展优化：引入子模优化算法

---

projects/app/src/pages/404.tsx

`/404` page translator failure causes navigation bar text flickering on redirected page load.

fix: page /404 translator not working bug

---

packages/service/common/file/image/controller.ts
packages/service/common/response/index.ts
packages/service/core/dataset/image/controller.ts
packages/service/core/workflow/dispatch/child/runTool.ts

fix: https://github.com/labring/FastGPT/issues/5377

fix: mcp not response output

---

projects/app/src/web/common/api/request.ts

在请求错误处理中，添加基础URL前缀以正确判断当前是否为外部链接页面。

fix(api): 修复二级路由下的页面判断逻辑

---

packages/global/core/workflow/utils.ts
projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/list.tsx
projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
projects/app/src/web/core/workflow/utils.ts

1. 工作流调用应用，单选的全局变量无法显示
2. 批量运行节点内部，未过滤批量运行节点的创建
3. 表单输入节点的输入，切换类型时重置默认值
4. 复制http节点，会渲染出废弃的输入

fix: node template bugs
